language: cpp
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/cmake
    - ${TRAVIS_BUILD_DIR}/deps/root
    - ${TRAVIS_BUILD_DIR}/deps/doxygen

branches:
  exclude:
    - gh-pages

env:
  global:
  - OMP_NUM_THREADS: 2
  - DOXYFILE: $TRAVIS_BUILD_DIR/docs/Doxyfile
  - secure: yyNmKB1C1bDyvbI/GWkDoUbBoVI+CIuCgftZ/RKnrynfjOe2uaJSVqo9s1L03Pth0mKsBFRAdq4rzLQ/q9v1FG+zVXwyP+gHqbb5SpvY1rNSjfS0JWjF2ZPNVEZ5ewJiV1adfvqen1ri+KB3CDXXi6BdXvmb0+g6ylnO5JuC3zvs60kXLUpAvRnfVMW8mDllEdVRvEVdjAnstiDd+G5U1WGK60JlBosOuvinkKiqTgcqfKHFojlYfoxTOkCtth4sP8fsxCQRP4kNmS7U9w8prFntWZP7n+kXKWfwLTvKg4RWntMt/f6jkQmMH2nDdvsPXvJzS0khPpQSQCIXIrLIcaHJRRTGv8Fg502RUrysgiOxdrcgRvH9AqFn9e48Sal1tkIHygvld7tifv92XowOsQ4VTiFI5PuZ8Ljr3L+SefwowTRK2R1Iz8flIgXHuWsDYbASi3oLPHMzsTXyLJxyoPKFNaXx2TM9S+73PXQcLUlQSdsvDb5AqqSDd5DUwBDSkixXACI+r33iDs64b8DQj8y7Ko0TTahPdmPjY+J9GPy4tLMeuhzvCy4Nfxiqhrf+wRcdWbKcOZsVDtMJPD4f1o1NZ8M8mRMR3YNU7WDbHAivULei01PZrtn0pPlHS8UO+MeCLB0W5KEQNo3CI0/nyuYwGAyytBwNaNwtaiKgMFY=
addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
    - g++-4.8
    - gcc-4.8
    - libx11-dev
    - libxpm-dev
    - libxft-dev
    - libxext-dev
    sources:
    - ubuntu-toolchain-r-test

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - cd "${TRAVIS_BUILD_DIR}" && . .ci/build_cmake.sh 
    - cd "${TRAVIS_BUILD_DIR}" && . .ci/build_root.sh 
    - cd "${TRAVIS_BUILD_DIR}" && . .ci/build_doxygen.sh 

script:
    - cd "${TRAVIS_BUILD_DIR}"
    - .ci/travis.sh

after_success:
- echo "${TRAVIS_BRANCH}"
- echo "${TRAVIS_PULL_REQUEST}"
- if [[ "${TRAVIS_BRANCH}" == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]] ; then echo "Updating docs" &&  cd "${TRAVIS_BUILD_DIR}" && .ci/build_docs.sh ; fi
